version: '3'

vars:
  APP_NAME: terraform-feature-toggles-provider

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - go build -o {{.APP_NAME}} *.go
    sources:
      - "*.go"
    generates:
      - "{{.APP_NAME}}"

  test:
    cmds:
      - go test -v ./... -cover

  tidy:
    cmds:
      - go mod tidy
